"""
Task 1 backbone pipeline.

This module is a thin, readable facade over the existing MPC implementation in
``project.model.simulation.mpc_simulation``. It makes Task 1 the main entry
point without moving the original, tested model code.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from ..simulation.mpc_simulation import (
    ControlAction,
    MPCConfig,
    run_mpc_simulation,
)


@dataclass(frozen=True)
class Task1RunConfig:
    team: str = "LVA"
    periods: int = 3
    horizon: int = 2
    n_mc: int = 10
    seed: int = 42
    control_mode: str = "policy"
    decision_every: int = 1
    write: bool = True
    use_parallel: bool = True
    task2_state_path: Optional[Path] = None
    task3_impact_path: Optional[Path] = None
    fixed_tau: Optional[float] = None
    fixed_m: Optional[float] = None
    fixed_u: Optional[float] = None


def _build_mpc_config(config: Task1RunConfig) -> MPCConfig:
    return MPCConfig(
        periods=int(config.periods),
        horizon=int(config.horizon),
        n_mc=int(config.n_mc),
        control_mode=str(config.control_mode).strip().lower(),
    )


def _build_fixed_action(config: Task1RunConfig) -> Optional[ControlAction]:
    if config.fixed_tau is None and config.fixed_m is None and config.fixed_u is None:
        return None

    return ControlAction(
        tau=float(config.fixed_tau if config.fixed_tau is not None else 1.0),
        m=float(config.fixed_m if config.fixed_m is not None else 0.0),
        u=float(config.fixed_u if config.fixed_u is not None else 0.0),
    )


def run_task1(config: Task1RunConfig):
    """
    Run the Task 1 MPC backbone.

    Returns
    -------
    tuple[pandas.DataFrame, pandas.DataFrame]
        Period log and summary generated by the underlying MPC model.
    """
    return run_mpc_simulation(
        focus_team=config.team.strip().upper(),
        seed=int(config.seed),
        cfg=_build_mpc_config(config),
        write=bool(config.write),
        use_parallel=bool(config.use_parallel),
        init_state_path=config.task2_state_path,
        task3_impact_path=config.task3_impact_path,
        decision_every=int(config.decision_every),
        fixed_action=_build_fixed_action(config),
    )


def run_task1_with_task2_state(
    task2_state_path: str | Path,
    *,
    config: Optional[Task1RunConfig] = None,
):
    """Run Task 1 using the roster-derived initial state from Task 2."""
    base = config or Task1RunConfig()
    return run_task1(
        Task1RunConfig(
            **{
                **base.__dict__,
                "task2_state_path": Path(task2_state_path),
            }
        )
    )


def run_task1_with_task3_shock(
    task3_impact_path: str | Path,
    *,
    config: Optional[Task1RunConfig] = None,
):
    """Run Task 1 with an expansion shock exported by Task 3."""
    base = config or Task1RunConfig()
    return run_task1(
        Task1RunConfig(
            **{
                **base.__dict__,
                "task3_impact_path": Path(task3_impact_path),
            }
        )
    )


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Run Task 1 as the model backbone.")
    parser.add_argument("--team", default="LVA")
    parser.add_argument("--periods", type=int, default=3)
    parser.add_argument("--horizon", type=int, default=2)
    parser.add_argument("--n-mc", type=int, default=10)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--control-mode", choices=["policy", "grid"], default="policy")
    parser.add_argument("--decision-every", type=int, default=1)
    parser.add_argument("--task2-state", default=None)
    parser.add_argument("--task3-impact", default=None)
    parser.add_argument("--fixed-tau", type=float, default=None)
    parser.add_argument("--fixed-m", type=float, default=None)
    parser.add_argument("--fixed-u", type=float, default=None)
    parser.add_argument("--no-write", action="store_true")
    parser.add_argument("--no-parallel", action="store_true")
    args = parser.parse_args(argv)

    period_log, summary = run_task1(
        Task1RunConfig(
            team=args.team,
            periods=args.periods,
            horizon=args.horizon,
            n_mc=args.n_mc,
            seed=args.seed,
            control_mode=args.control_mode,
            decision_every=args.decision_every,
            write=not args.no_write,
            use_parallel=not args.no_parallel,
            task2_state_path=Path(args.task2_state) if args.task2_state else None,
            task3_impact_path=Path(args.task3_impact) if args.task3_impact else None,
            fixed_tau=args.fixed_tau,
            fixed_m=args.fixed_m,
            fixed_u=args.fixed_u,
        )
    )
    print(period_log.to_string(index=False))
    print("")
    print(summary.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
